#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
#ifndef MAPBOXMAPOBJC_SWIFT_H
#define MAPBOXMAPOBJC_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import MapboxMaps;
@import ObjectiveC;
@import QuartzCore;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MapboxMapObjC",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


@class MBXExpression;
@class NSString;
@class NSNumber;
@class MBXValue;
@class MBXStyleTransition;

SWIFT_CLASS("_TtC13MapboxMapObjC25FillExtrusionLayerBuilder")
@interface FillExtrusionLayerBuilder : NSObject
- (void)filter:(MBXExpression * _Nullable)value;
- (void)source:(NSString * _Nullable)value;
- (void)sourceLayer:(NSString * _Nullable)value;
- (void)minZoom:(NSNumber * _Nullable)value;
- (void)maxZoom:(NSNumber * _Nullable)value;
- (void)visibility:(MBXValue * _Nullable)value;
- (void)fillExtrusionAmbientOcclusionIntensity:(MBXValue * _Nullable)value;
- (void)fillExtrusionAmbientOcclusionIntensityTransition:(MBXStyleTransition * _Nullable)value;
- (void)fillExtrusionAmbientOcclusionRadius:(MBXValue * _Nullable)value;
- (void)fillExtrusionAmbientOcclusionRadiusTransition:(MBXStyleTransition * _Nullable)value;
- (void)fillExtrusionBase:(MBXValue * _Nullable)value;
- (void)fillExtrusionBaseTransition:(MBXStyleTransition * _Nullable)value;
- (void)fillExtrusionColor:(MBXValue * _Nullable)value;
- (void)fillExtrusionColorTransition:(MBXStyleTransition * _Nullable)value;
- (void)fillExtrusionHeight:(MBXValue * _Nullable)value;
- (void)fillExtrusionHeightTransition:(MBXStyleTransition * _Nullable)value;
- (void)fillExtrusionOpacity:(MBXValue * _Nullable)value;
- (void)fillExtrusionOpacityTransition:(MBXStyleTransition * _Nullable)value;
- (void)fillExtrusionPattern:(MBXValue * _Nullable)value;
- (void)fillExtrusionPatternTransition:(MBXStyleTransition * _Nullable)value;
- (void)fillExtrusionTranslate:(MBXValue * _Nullable)value;
- (void)fillExtrusionTranslateTransition:(MBXStyleTransition * _Nullable)value;
- (void)fillExtrusionTranslateAnchor:(MBXValue * _Nonnull)value;
- (void)fillExtrusionVerticalGradient:(MBXValue * _Nullable)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Whether extruded geometries are lit relative to the map or viewport.
typedef SWIFT_ENUM(NSInteger, MBXAnchor, open) {
/// The position of the light source is aligned to the rotation of the map.
  MBXAnchorMap = 0,
/// The position of the light source is aligned to the rotation of the viewport.
  MBXAnchorViewport = 1,
};


SWIFT_CLASS("_TtC13MapboxMapObjC13MBXCancelable")
@interface MBXCancelable : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Orientation of circle when map is pitched.
typedef SWIFT_ENUM(NSInteger, MBXCirclePitchAlignment, open) {
/// The circle is aligned to the plane of the map.
  MBXCirclePitchAlignmentMap = 0,
/// The circle is aligned to the plane of the viewport.
  MBXCirclePitchAlignmentViewport = 1,
};

/// Controls the scaling behavior of the circle when the map is pitched.
typedef SWIFT_ENUM(NSInteger, MBXCirclePitchScale, open) {
/// Circles are scaled according to their apparent distance to the camera.
  MBXCirclePitchScaleMap = 0,
/// Circles are not scaled.
  MBXCirclePitchScaleViewport = 1,
};

/// Controls the frame of reference for <code>circle-translate</code>.
typedef SWIFT_ENUM(NSInteger, MBXCircleTranslateAnchor, open) {
/// The circle is translated relative to the map.
  MBXCircleTranslateAnchorMap = 0,
/// The circle is translated relative to the viewport.
  MBXCircleTranslateAnchorViewport = 1,
};

typedef SWIFT_ENUM(NSInteger, MBXEncoding, open) {
/// Terrarium format PNG tiles. See https://aws.amazon.com/es/public-datasets/terrain/ for more info.
  MBXEncodingTerrarium = 0,
/// Mapbox Terrain RGB tiles. See https://www.mapbox.com/help/access-elevation-data/#mapbox-terrain-rgb for more info.
  MBXEncodingMapbox = 1,
};

enum MBXOperator : NSInteger;

SWIFT_CLASS("_TtC13MapboxMapObjC13MBXExpression")
@interface MBXExpression : NSObject
+ (MBXExpression * _Nonnull)createWithOperator:(enum MBXOperator)operator_ SWIFT_WARN_UNUSED_RESULT;
+ (MBXExpression * _Nonnull)createWithOperator:(enum MBXOperator)operator_ arguments:(NSArray * _Nonnull)arguments SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Controls the frame of reference for <code>fill-extrusion-translate</code>.
typedef SWIFT_ENUM(NSInteger, MBXFillExtrusionTranslateAnchor, open) {
/// The fill extrusion is translated relative to the map.
  MBXFillExtrusionTranslateAnchorMap = 0,
/// The fill extrusion is translated relative to the viewport.
  MBXFillExtrusionTranslateAnchorViewport = 1,
};

/// Controls the frame of reference for <code>fill-translate</code>.
typedef SWIFT_ENUM(NSInteger, MBXFillTranslateAnchor, open) {
/// The fill is translated relative to the map.
  MBXFillTranslateAnchorMap = 0,
/// The fill is translated relative to the viewport.
  MBXFillTranslateAnchorViewport = 1,
};

/// Direction of light source when map is rotated.
typedef SWIFT_ENUM(NSInteger, MBXHillshadeIlluminationAnchor, open) {
/// The hillshade illumination is relative to the north direction.
  MBXHillshadeIlluminationAnchorMap = 0,
/// The hillshade illumination is relative to the top of the viewport.
  MBXHillshadeIlluminationAnchorViewport = 1,
};

/// Part of the icon placed closest to the anchor.
typedef SWIFT_ENUM(NSInteger, MBXIconAnchor, open) {
/// The center of the icon is placed closest to the anchor.
  MBXIconAnchorCenter = 0,
/// The left side of the icon is placed closest to the anchor.
  MBXIconAnchorLeft = 1,
/// The right side of the icon is placed closest to the anchor.
  MBXIconAnchorRight = 2,
/// The top of the icon is placed closest to the anchor.
  MBXIconAnchorTop = 3,
/// The bottom of the icon is placed closest to the anchor.
  MBXIconAnchorBottom = 4,
/// The top left corner of the icon is placed closest to the anchor.
  MBXIconAnchorTopLeft = 5,
/// The top right corner of the icon is placed closest to the anchor.
  MBXIconAnchorTopRight = 6,
/// The bottom left corner of the icon is placed closest to the anchor.
  MBXIconAnchorBottomLeft = 7,
/// The bottom right corner of the icon is placed closest to the anchor.
  MBXIconAnchorBottomRight = 8,
};

/// Orientation of icon when map is pitched.
typedef SWIFT_ENUM(NSInteger, MBXIconPitchAlignment, open) {
/// The icon is aligned to the plane of the map.
  MBXIconPitchAlignmentMap = 0,
/// The icon is aligned to the plane of the viewport.
  MBXIconPitchAlignmentViewport = 1,
/// Automatically matches the value of {@link ICON_ROTATION_ALIGNMENT}.
  MBXIconPitchAlignmentAuto = 2,
};

/// In combination with <code>symbol-placement</code>, determines the rotation behavior of icons.
typedef SWIFT_ENUM(NSInteger, MBXIconRotationAlignment, open) {
/// When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_POINT}, aligns icons east-west. When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_LINE} or {@link Property#SYMBOL_PLACEMENT_LINE_CENTER}, aligns icon x-axes with the line.
  MBXIconRotationAlignmentMap = 0,
/// Produces icons whose x-axes are aligned with the x-axis of the viewport, regardless of the value of {@link SYMBOL_PLACEMENT}.
  MBXIconRotationAlignmentViewport = 1,
/// When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_POINT}, this is equivalent to {@link Property#ICON_ROTATION_ALIGNMENT_VIEWPORT}. When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_LINE} or {@link Property#SYMBOL_PLACEMENT_LINE_CENTER}, this is equivalent to {@link Property#ICON_ROTATION_ALIGNMENT_MAP}.
  MBXIconRotationAlignmentAuto = 2,
};

/// Scales the icon to fit around the associated text.
typedef SWIFT_ENUM(NSInteger, MBXIconTextFit, open) {
/// The icon is displayed at its intrinsic aspect ratio.
  MBXIconTextFitNone = 0,
/// The icon is scaled in the x-dimension to fit the width of the text.
  MBXIconTextFitWidth = 1,
/// The icon is scaled in the y-dimension to fit the height of the text.
  MBXIconTextFitHeight = 2,
/// The icon is scaled in both x- and y-dimensions.
  MBXIconTextFitBoth = 3,
};

/// Controls the frame of reference for <code>icon-translate</code>.
typedef SWIFT_ENUM(NSInteger, MBXIconTranslateAnchor, open) {
/// Icons are translated relative to the map.
  MBXIconTranslateAnchorMap = 0,
/// Icons are translated relative to the viewport.
  MBXIconTranslateAnchorViewport = 1,
};

/// The display of line endings.
typedef SWIFT_ENUM(NSInteger, MBXLineCap, open) {
/// A cap with a squared-off end which is drawn to the exact endpoint of the line.
  MBXLineCapButt = 0,
/// A cap with a rounded end which is drawn beyond the endpoint of the line at a radius of one-half of the line’s width and centered on the endpoint of the line.
  MBXLineCapRound = 1,
/// A cap with a squared-off end which is drawn beyond the endpoint of the line at a distance of one-half of the line’s width.
  MBXLineCapSquare = 2,
};

/// The display of lines when joining.
typedef SWIFT_ENUM(NSInteger, MBXLineJoin, open) {
/// A join with a squared-off end which is drawn beyond the endpoint of the line at a distance of one-half of the line’s width.
  MBXLineJoinBevel = 0,
/// A join with a rounded end which is drawn beyond the endpoint of the line at a radius of one-half of the line’s width and centered on the endpoint of the line.
  MBXLineJoinRound = 1,
/// A join with a sharp, angled corner which is drawn with the outer sides beyond the endpoint of the path until they meet.
  MBXLineJoinMiter = 2,
};

/// Controls the frame of reference for <code>line-translate</code>.
typedef SWIFT_ENUM(NSInteger, MBXLineTranslateAnchor, open) {
/// The line is translated relative to the map.
  MBXLineTranslateAnchorMap = 0,
/// The line is translated relative to the viewport.
  MBXLineTranslateAnchorViewport = 1,
};

typedef SWIFT_ENUM(NSInteger, MBXOperator, open) {
/// For two inputs, returns the result of subtracting the second input from the first. For a single input, returns the result of subtracting it from 0.
  MBXOperatorSubtract = 0,
/// Logical negation. Returns <code>true</code> if the input is <code>false</code>, and <code>false</code> if the input is <code>true</code>.
  MBXOperatorNot = 1,
/// Returns <code>true</code> if the input values are not equal, <code>false</code> otherwise. The comparison is strictly typed: values of different runtime types are always considered unequal. Cases where the types are known to be different at parse time are considered invalid and will produce a parse error. Accepts an optional <code>collator</code> argument to control locale-dependent string comparisons.
  MBXOperatorNeq = 2,
/// Returns the product of the inputs.
  MBXOperatorProduct = 3,
/// Returns the result of floating point division of the first input by the second.
  MBXOperatorDivision = 4,
/// Returns the remainder after integer division of the first input by the second.
  MBXOperatorMod = 5,
/// Returns the result of raising the first input to the power specified by the second.
  MBXOperatorPow = 6,
/// Returns the sum of the inputs.
  MBXOperatorSum = 7,
/// Returns <code>true</code> if the first input is strictly less than the second, <code>false</code> otherwise. The arguments are required to be either both strings or both numbers; if during evaluation they are not, expression evaluation produces an error. Cases where this constraint is known not to hold at parse time are considered in valid and will produce a parse error. Accepts an optional <code>collator</code> argument to control locale-dependent string comparisons.
  MBXOperatorLt = 8,
/// Returns <code>true</code> if the first input is less than or equal to the second, <code>false</code> otherwise. The arguments are required to be either both strings or both numbers; if during evaluation they are not, expression evaluation produces an error. Cases where this constraint is known not to hold at parse time are considered in valid and will produce a parse error. Accepts an optional <code>collator</code> argument to control locale-dependent string comparisons.
  MBXOperatorLte = 9,
/// Returns <code>true</code> if the input values are equal, <code>false</code> otherwise. The comparison is strictly typed: values of different runtime types are always considered unequal. Cases where the types are known to be different at parse time are considered invalid and will produce a parse error. Accepts an optional <code>collator</code> argument to control locale-dependent string comparisons.
  MBXOperatorEq = 10,
/// Returns <code>true</code> if the first input is strictly greater than the second, <code>false</code> otherwise. The arguments are required to be either both strings or both numbers; if during evaluation they are not, expression evaluation produces an error. Cases where this constraint is known not to hold at parse time are considered in valid and will produce a parse error. Accepts an optional <code>collator</code> argument to control locale-dependent string comparisons.
  MBXOperatorGt = 11,
/// Returns <code>true</code> if the first input is greater than or equal to the second, <code>false</code> otherwise. The arguments are required to be either both strings or both numbers; if during evaluation they are not, expression evaluation produces an error. Cases where this constraint is known not to hold at parse time are considered in valid and will produce a parse error. Accepts an optional <code>collator</code> argument to control locale-dependent string comparisons.
  MBXOperatorGte = 12,
/// Returns the absolute value of the input.
  MBXOperatorAbs = 13,
/// Returns the value of a cluster property accumulated so far. Can only be used in the <code>clusterProperties</code> option of a clustered GeoJSON source.
  MBXOperatorAccumulated = 14,
/// Returns the arccosine of the input.
  MBXOperatorAcos = 15,
/// Returns <code>true</code> if all the inputs are <code>true</code>, <code>false</code> otherwise. The inputs are evaluated in order, and evaluation is short-circuiting: once an input expression evaluates to <code>false</code>, the result is <code>false</code> and no further input expressions are evaluated.
  MBXOperatorAll = 16,
/// Returns <code>true</code> if any of the inputs are <code>true</code>, <code>false</code> otherwise. The inputs are evaluated in order, and evaluation is short-circuiting: once an input expression evaluates to <code>true</code>, the result is <code>true</code> and no further input expressions are evaluated.
  MBXOperatorAny = 17,
/// Asserts that the input is an array (optionally with a specific item type and length).  If, when the input expression is evaluated, it is not of the asserted type, then this assertion will cause the whole expression to be aborted.
  MBXOperatorArray = 18,
/// Returns the arcsine of the input.
  MBXOperatorAsin = 19,
/// Retrieves an item from an array.
  MBXOperatorAt = 20,
/// Returns the arctangent of the input.
  MBXOperatorAtan = 21,
/// Asserts that the input value is a boolean. If multiple values are provided, each one is evaluated in order until a boolean is obtained. If none of the inputs are booleans, the expression is an error.
  MBXOperatorBoolean = 22,
/// Selects the first output whose corresponding test condition evaluates to true, or the fallback value otherwise.
  MBXOperatorSwitchCase = 23,
/// Returns the smallest integer that is greater than or equal to the input.
  MBXOperatorCeil = 24,
/// Evaluates each expression in turn until the first valid value is obtained. Invalid values are <code>null</code> and <a href="#types-image"><code>'image'</code></a> expressions that are unavailable in the style. If all values are invalid, <code>coalesce</code> returns the first value listed.
  MBXOperatorCoalesce = 25,
/// Returns a <code>collator</code> for use in locale-dependent comparison operations. The <code>case-sensitive</code> and <code>diacritic-sensitive</code> options default to <code>false</code>. The <code>locale</code> argument specifies the IETF language tag of the locale to use. If none is provided, the default locale is used. If the requested locale is not available, the <code>collator</code> will use a system-defined fallback locale. Use <code>resolved-locale</code> to test the results of locale fallback behavior.
  MBXOperatorCollator = 26,
/// Returns a <code>string</code> consisting of the concatenation of the inputs. Each input is converted to a string as if by <code>to-string</code>.
  MBXOperatorConcat = 27,
/// Returns the cosine of the input.
  MBXOperatorCos = 28,
/// Returns the shortest distance in meters between the evaluated feature and the input geometry. The input value can be a valid GeoJSON of type <code>Point</code>, <code>MultiPoint</code>, <code>LineString</code>, <code>MultiLineString</code>, <code>Polygon</code>, <code>MultiPolygon</code>, <code>Feature</code>, or <code>FeatureCollection</code>. Distance values returned may vary in precision due to loss in precision from encoding geometries, particularly below zoom level 13.
  MBXOperatorDistance = 29,
/// Returns the distance of a <code>symbol</code> instance from the center of the map. The distance is measured in pixels divided by the height of the map container. It measures 0 at the center, decreases towards the camera and increase away from the camera. For example, if the height of the map is 1000px, a value of -1 means 1000px away from the center towards the camera, and a value of 1 means a distance of 1000px away from the camera from the center. <code>["distance-from-center"]</code> may only be used in the <code>filter</code> expression for a <code>symbol</code> layer.
  MBXOperatorDistanceFromCenter = 30,
/// Returns the input string converted to lowercase. Follows the Unicode Default Case Conversion algorithm and the locale-insensitive case mappings in the Unicode Character Database.
  MBXOperatorDowncase = 31,
/// Returns the mathematical constant e.
  MBXOperatorE = 32,
/// Retrieves a property value from the current feature’s state. Returns <code>null</code> if the requested property is not present on the feature’s state. A feature’s state is not part of the GeoJSON or vector tile data, and must be set programmatically on each feature. Features are identified by their <code>id</code> attribute, which must be an integer or a string that can be cast to an integer. Note that [“feature-state”] can only be used with paint properties that support data-driven styling.
  MBXOperatorFeatureState = 33,
/// Returns the largest integer that is less than or equal to the input.
  MBXOperatorFloor = 34,
/// Returns a <code>formatted</code> string for displaying mixed-format text in the <code>text-field</code> property. The input may contain a string literal or expression, including an <a href="#types-image"><code>'image'</code></a> expression. Strings may be followed by a style override object that supports the following properties:
/// <ul>
///   <li>
///     <code>"text-font"</code>: Overrides the font stack specified by the root layout property.
///   </li>
///   <li>
///     <code>"text-color"</code>: Overrides the color specified by the root paint property.
///   </li>
///   <li>
///     <code>"font-scale"</code>: Applies a scaling factor on <code>text-size</code> as specified by the root layout property.
///   </li>
/// </ul>
  MBXOperatorFormat = 35,
/// Returns the feature’s geometry type: <code>Point</code>, <code>LineString</code> or <code>Polygon</code>. <code>Multi*</code> feature types return the singular forms.
  MBXOperatorGeometryType = 36,
/// Retrieves a property value from the current feature’s properties, or from another object if a second argument is provided. Returns <code>null</code> if the requested property is missing.
  MBXOperatorGet = 37,
/// Tests for the presence of an property value in the current feature’s properties, or from another object if a second argument is provided.
  MBXOperatorHas = 38,
/// Returns the kernel density estimation of a pixel in a heatmap layer, which is a relative measure of how many data points are crowded around a particular pixel. Can only be used in the <code>heatmap-color</code> property.
  MBXOperatorHeatmapDensity = 39,
/// Returns the feature’s id, if it has one.
  MBXOperatorId = 40,
/// Returns a <a href="/mapbox-gl-js/style-spec/types/#resolvedimage"><code>ResolvedImage</code></a> for use in <a href="/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-image"><code>icon-image</code></a>, <code>*-pattern</code> entries, and as a section in the <a href="#types-format"><code>'format'</code></a> expression. A <a href="#coalesce"><code>'coalesce'</code></a> expression containing <code>image</code> expressions will evaluate to the first listed image that is currently in the style. This validation process is synchronous and requires the image to have been added to the style before requesting it in the <code>'image'</code> argument.
  MBXOperatorImage = 41,
/// Determines whether an item exists in an array or a substring exists in a string. In the specific case when the second and third arguments are string literals, you must wrap at least one of them in a <a href="#types-literal"><code>literal</code></a> expression to hint correct interpretation to the <a href="#type-system">type system</a>.
  MBXOperatorInExpression = 42,
/// Returns the first position at which an item can be found in an array or a substring can be found in a string, or <code>-1</code> if the input cannot be found. Accepts an optional index from where to begin the search.
  MBXOperatorIndexOf = 43,
/// Produces continuous, smooth results by interpolating between pairs of input and output values (“stops”). The <code>input</code> may be any numeric expression (e.g., <code>["get", "population"]</code>). Stop inputs must be numeric literals in strictly ascending order. The output type must be <code>number</code>, <code>array<number></code>, or <code>color</code>.
/// Interpolation types:
/// <ul>
///   <li>
///     <code>["linear"]</code>: Interpolates linearly between the pair of stops just less than and just greater than the input.
///   </li>
///   <li>
///     <code>["exponential", base]</code>: Interpolates exponentially between the stops just less than and just greater than the input. <code>base</code> controls the rate at which the output increases: higher values make the output increase more towards the high end of the range. With values close to 1 the output increases linearly.
///   </li>
///   <li>
///     <code>["cubic-bezier", x1, y1, x2, y2]</code>: Interpolates using the cubic bezier curve defined by the given control points.
///   </li>
/// </ul>
  MBXOperatorInterpolate = 44,
/// Returns <code>true</code> if the input string is expected to render legibly. Returns <code>false</code> if the input string contains sections that cannot be rendered without potential loss of meaning (e.g. Indic scripts that require complex text shaping, or right-to-left scripts if the the <code>mapbox-gl-rtl-text</code> plugin is not in use in Mapbox GL JS).
  MBXOperatorIsSupportedScript = 45,
/// Returns the length of an array or string.
  MBXOperatorLength = 46,
/// Binds expressions to named variables, which can then be referenced in the result expression using [“var”, “variable_name”].
  MBXOperatorLetExpression = 47,
/// Returns the progress along a gradient line. Can only be used in the <code>line-gradient</code> property.
  MBXOperatorLineProgress = 48,
/// Provides a literal array or object value.
  MBXOperatorLiteral = 49,
/// Returns the natural logarithm of the input.
  MBXOperatorLn = 50,
/// Returns mathematical constant ln(2).
  MBXOperatorLn2 = 51,
/// Returns the base-ten logarithm of the input.
  MBXOperatorLog10 = 52,
/// Returns the base-two logarithm of the input.
  MBXOperatorLog2 = 53,
/// Selects the output for which the label value matches the input value, or the fallback value if no match is found. The input can be any expression (for example, <code>["get", "building_type"]</code>). Each label must be unique, and must be either:
/// <ul>
///   <li>
///     a single literal value; or
///   </li>
///   <li>
///     an array of literal values, the values of which must be all strings or all numbers (for example <code>[100, 101]</code> or <code>["c", "b"]</code>).
///   </li>
/// </ul>
/// The input matches if any of the values in the array matches using strict equality, similar to the <code>"in"</code> operator.
/// If the input type does not match the type of the labels, the result will be the fallback value.
  MBXOperatorMatch = 54,
/// Returns the maximum value of the inputs.
  MBXOperatorMax = 55,
/// Returns the minimum value of the inputs.
  MBXOperatorMin = 56,
/// Asserts that the input value is a number. If multiple values are provided, each one is evaluated in order until a number is obtained. If none of the inputs are numbers, the expression is an error.
  MBXOperatorNumber = 57,
/// Converts the input number into a string representation using the providing formatting rules. If set, the <code>locale</code> argument specifies the locale to use, as a BCP 47 language tag. If set, the <code>currency</code> argument specifies an ISO 4217 code to use for currency-style formatting. If set, the <code>unit</code> argument specifies a <a href="https://tc39.es/proposal-unified-intl-numberformat/section6/locales-currencies-tz_proposed_out.html#sec-issanctionedsimpleunitidentifier">simple ECMAScript unit</a> to use for unit-style formatting. If set, the <code>min-fraction-digits</code> and <code>max-fraction-digits</code> arguments specify the minimum and maximum number of fractional digits to include.
  MBXOperatorNumberFormat = 58,
/// Asserts that the input value is an object. If multiple values are provided, each one is evaluated in order until an object is obtained. If none of the inputs are objects, the expression is an error.
  MBXOperatorObjectExpression = 59,
/// Returns the mathematical constant pi.
  MBXOperatorPi = 60,
/// Returns the current pitch in degrees. <code>["pitch"]</code> may only be used in the <code>filter</code> expression for a <code>symbol</code> layer.
  MBXOperatorPitch = 61,
/// Returns the feature properties object.  Note that in some cases, it may be more efficient to use <code>["get", "property_name"]</code> directly.
  MBXOperatorProperties = 62,
/// Returns the IETF language tag of the locale being used by the provided <code>collator</code>. This can be used to determine the default system locale, or to determine if a requested locale was successfully loaded.
  MBXOperatorResolvedLocale = 63,
/// Creates a color value from red, green, and blue components, which must range between 0 and 255, and an alpha component of 1. If any component is out of range, the expression is an error.
  MBXOperatorRgb = 64,
/// Creates a color value from red, green, blue components, which must range between 0 and 255, and an alpha component which must range between 0 and 1. If any component is out of range, the expression is an error.
  MBXOperatorRgba = 65,
/// Rounds the input to the nearest integer. Halfway values are rounded away from zero. For example, <code>["round", -1.5]</code> evaluates to -2.
  MBXOperatorRound = 66,
/// Returns the sine of the input.
  MBXOperatorSin = 67,
/// Returns the distance of a point on the sky from the sun position. Returns 0 at sun position and 1 when the distance reaches <code>sky-gradient-radius</code>. Can only be used in the <code>sky-gradient</code> property.
  MBXOperatorSkyRadialProgress = 68,
/// Returns an item from an array or a substring from a string from a specified start index, or between a start index and an end index if set. The return value is inclusive of the start index but not of the end index.
  MBXOperatorSlice = 69,
/// Returns the square root of the input.
  MBXOperatorSqrt = 70,
/// Produces discrete, stepped results by evaluating a piecewise-constant function defined by pairs of input and output values (“stops”). The <code>input</code> may be any numeric expression (e.g., <code>["get", "population"]</code>). Stop inputs must be numeric literals in strictly ascending order. Returns the output value of the stop just less than the input, or the first output if the input is less than the first stop.
  MBXOperatorStep = 71,
/// Asserts that the input value is a string. If multiple values are provided, each one is evaluated in order until a string is obtained. If none of the inputs are strings, the expression is an error.
  MBXOperatorString = 72,
/// Returns the tangent of the input.
  MBXOperatorTan = 73,
/// Converts the input value to a boolean. The result is <code>false</code> when then input is an empty string, 0, <code>false</code>, <code>null</code>, or <code>NaN</code>; otherwise it is <code>true</code>.
  MBXOperatorToBoolean = 74,
/// Converts the input value to a color. If multiple values are provided, each one is evaluated in order until the first successful conversion is obtained. If none of the inputs can be converted, the expression is an error.
  MBXOperatorToColor = 75,
/// Converts the input value to a number, if possible. If the input is <code>null</code> or <code>false</code>, the result is 0. If the input is <code>true</code>, the result is 1. If the input is a string, it is converted to a number as specified by the <a href="https://tc39.github.io/ecma262/#sec-tonumber-applied-to-the-string-type">“ToNumber Applied to the String Type” algorithm</a> of the ECMAScript Language Specification. If multiple values are provided, each one is evaluated in order until the first successful conversion is obtained. If none of the inputs can be converted, the expression is an error.
  MBXOperatorToNumber = 76,
/// Returns a four-element array containing the input color’s red, green, blue, and alpha components, in that order.
  MBXOperatorToRgba = 77,
/// Converts the input value to a string. If the input is <code>null</code>, the result is <code>""</code>. If the input is a <a href="#types-boolean"><code>boolean</code></a>, the result is <code>"true"</code> or <code>"false"</code>. If the input is a number, it is converted to a string as specified by the <a href="https://tc39.github.io/ecma262/#sec-tostring-applied-to-the-number-type">“NumberToString” algorithm</a> of the ECMAScript Language Specification. If the input is a <a href="#color"><code>color</code></a>, it is converted to a string of the form <code>"rgba(r,g,b,a)"</code>, where <code>r</code>, <code>g</code>, and <code>b</code> are numerals ranging from 0 to 255, and <code>a</code> ranges from 0 to 1. If the input is an <a href="#types-image"><code>'image'</code></a> expression, <code>'to-string'</code> returns the image name. Otherwise, the input is converted to a string in the format specified by the <a href="https://tc39.github.io/ecma262/#sec-json.stringify"><code>JSON.stringify</code></a> function of the ECMAScript Language Specification.
  MBXOperatorToString = 78,
/// Returns a string describing the type of the given value.
  MBXOperatorTypeofExpression = 79,
/// Returns the input string converted to uppercase. Follows the Unicode Default Case Conversion algorithm and the locale-insensitive case mappings in the Unicode Character Database.
  MBXOperatorUpcase = 80,
/// References variable bound using “let”.
  MBXOperatorVarExpression = 81,
/// Returns <code>true</code> if the evaluated feature is fully contained inside a boundary of the input geometry, <code>false</code> otherwise. The input value can be a valid GeoJSON of type <code>Polygon</code>, <code>MultiPolygon</code>, <code>Feature</code>, or <code>FeatureCollection</code>. Supported features for evaluation:
/// <ul>
///   <li>
///     <code>Point</code>: Returns <code>false</code> if a point is on the boundary or falls outside the boundary.
///   </li>
///   <li>
///     <code>LineString</code>: Returns <code>false</code> if any part of a line falls outside the boundary, the line intersects the boundary, or a line’s endpoint is on the boundary.
///   </li>
/// </ul>
  MBXOperatorWithin = 82,
/// Returns the current zoom level.  Note that in style layout and paint properties, [“zoom”] may only appear as the input to a top-level “step” or “interpolate” expression.
  MBXOperatorZoom = 83,
/// Interpolates linearly between the pair of stops just less than and just greater than the input
  MBXOperatorLinear = 84,
/// <code>["exponential", base]</code>
/// Interpolates exponentially between the stops just less than and just
/// greater than the input. base controls the rate at which the output increases: higher values make the output
/// increase more towards the high end of the range.
/// With values close to 1 the output increases linearly.
  MBXOperatorExponential = 85,
/// <code>["cubic-bezier", x1, y1, x2, y2]</code>
/// Interpolates using the cubic bezier curve defined by the given control points.
  MBXOperatorCubicBezier = 86,
};

typedef SWIFT_ENUM(NSInteger, MBXOrnamentVisibility, open) {
  MBXOrnamentVisibilityAdaptive = 0,
  MBXOrnamentVisibilityHidden = 1,
  MBXOrnamentVisibilityVisible = 2,
};

typedef SWIFT_ENUM(NSInteger, MBXPuckBearingSource, open) {
  MBXPuckBearingSourceHeading = 0,
  MBXPuckBearingSourceCourse = 1,
};

/// The resampling/interpolation method to use for overscaling, also known as texture magnification filter
typedef SWIFT_ENUM(NSInteger, MBXRasterResampling, open) {
/// (Bi)linear filtering interpolates pixel values using the weighted average of the four closest original source pixels creating a smooth but blurry look when overscaled
  MBXRasterResamplingLinear = 0,
/// Nearest neighbor filtering interpolates pixel values using the nearest original source pixel creating a sharp but pixelated look when overscaled
  MBXRasterResamplingNearest = 1,
};


SWIFT_CLASS("_TtC13MapboxMapObjC16MBXResolvedImage")
@interface MBXResolvedImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC13MapboxMapObjC20MBXResolvedImageData")
@interface MBXResolvedImageData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The type of the sky
typedef SWIFT_ENUM(NSInteger, MBXSkyType, open) {
/// Renders the sky with a gradient that can be configured with {@link SKY_GRADIENT_RADIUS} and {@link SKY_GRADIENT}.
  MBXSkyTypeGradient = 0,
/// Renders the sky with a simulated atmospheric scattering algorithm, the sun direction can be attached to the light position or explicitly set through {@link SKY_ATMOSPHERE_SUN}.
  MBXSkyTypeAtmosphere = 1,
};

typedef SWIFT_ENUM(NSInteger, MBXSourceType, open) {
/// A vector tile source.
  MBXSourceTypeVector = 0,
/// A raster tile source.
  MBXSourceTypeRaster = 1,
/// A raster DEM source.
  MBXSourceTypeRasterDem = 2,
/// A GeoJSON source.
  MBXSourceTypeGeoJson = 3,
/// An image source.
  MBXSourceTypeImage = 4,
/// A model source
  MBXSourceTypeModel = 5,
};

/// The name of the projection to be used for rendering the map.
typedef SWIFT_ENUM(NSInteger, MBXStyleProjectionName, open) {
/// The Mercator projection is the default projection.
  MBXStyleProjectionNameMercator = 0,
/// A globe projection.
  MBXStyleProjectionNameGlobe = 1,
};


SWIFT_CLASS("_TtC13MapboxMapObjC18MBXStyleTransition")
@interface MBXStyleTransition : NSObject
- (nonnull instancetype)initWithDuration:(double)duration delay:(double)delay OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Label placement relative to its geometry.
typedef SWIFT_ENUM(NSInteger, MBXSymbolPlacement, open) {
/// The label is placed at the point where the geometry is located.
  MBXSymbolPlacementPoint = 0,
/// The label is placed along the line of the geometry. Can only be used on LineString and Polygon geometries.
  MBXSymbolPlacementLine = 1,
/// The label is placed at the center of the line of the geometry. Can only be used on LineString and Polygon geometries. Note that a single feature in a vector tile may contain multiple line geometries.
  MBXSymbolPlacementLineCenter = 2,
};

/// Determines whether overlapping symbols in the same layer are rendered in the order that they appear in the data source or by their y-position relative to the viewport. To control the order and prioritization of symbols otherwise, use <code>symbol-sort-key</code>.
typedef SWIFT_ENUM(NSInteger, MBXSymbolZOrder, open) {
/// Sorts symbols by symbol sort key if set. Otherwise, sorts symbols by their y-position relative to the viewport if {@link ICON_ALLOW_OVERLAP} or {@link TEXT_ALLOW_OVERLAP} is set to {@link TRUE} or {@link ICON_IGNORE_PLACEMENT} or {@link TEXT_IGNORE_PLACEMENT} is {@link FALSE}.
  MBXSymbolZOrderAuto = 0,
/// Sorts symbols by their y-position relative to the viewport if {@link ICON_ALLOW_OVERLAP} or {@link TEXT_ALLOW_OVERLAP} is set to {@link TRUE} or {@link ICON_IGNORE_PLACEMENT} or {@link TEXT_IGNORE_PLACEMENT} is {@link FALSE}.
  MBXSymbolZOrderViewportY = 1,
/// Sorts symbols by symbol sort key if set. Otherwise, no sorting is applied; symbols are rendered in the same order as the source data.
  MBXSymbolZOrderSource = 2,
};


SWIFT_CLASS("_TtC13MapboxMapObjC10MBXTerrain")
@interface MBXTerrain : NSObject
- (nonnull instancetype)initWithSourceId:(NSString * _Nonnull)sourceId OBJC_DESIGNATED_INITIALIZER;
/// Exaggerates the elevation of the terrain by multiplying the data from the DEM with this value.
@property (nonatomic, strong) MBXValue * _Nullable exaggeration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Part of the text placed closest to the anchor.
typedef SWIFT_ENUM(NSInteger, MBXTextAnchor, open) {
/// The center of the text is placed closest to the anchor.
  MBXTextAnchorCenter = 0,
/// The left side of the text is placed closest to the anchor.
  MBXTextAnchorLeft = 1,
/// The right side of the text is placed closest to the anchor.
  MBXTextAnchorRight = 2,
/// The top of the text is placed closest to the anchor.
  MBXTextAnchorTop = 3,
/// The bottom of the text is placed closest to the anchor.
  MBXTextAnchorBottom = 4,
/// The top left corner of the text is placed closest to the anchor.
  MBXTextAnchorTopLeft = 5,
/// The top right corner of the text is placed closest to the anchor.
  MBXTextAnchorTopRight = 6,
/// The bottom left corner of the text is placed closest to the anchor.
  MBXTextAnchorBottomLeft = 7,
/// The bottom right corner of the text is placed closest to the anchor.
  MBXTextAnchorBottomRight = 8,
};

/// Text justification options.
typedef SWIFT_ENUM(NSInteger, MBXTextJustify, open) {
/// The text is aligned towards the anchor position.
  MBXTextJustifyAuto = 0,
/// The text is aligned to the left.
  MBXTextJustifyLeft = 1,
/// The text is centered.
  MBXTextJustifyCenter = 2,
/// The text is aligned to the right.
  MBXTextJustifyRight = 3,
};

/// Orientation of text when map is pitched.
typedef SWIFT_ENUM(NSInteger, MBXTextPitchAlignment, open) {
/// The text is aligned to the plane of the map.
  MBXTextPitchAlignmentMap = 0,
/// The text is aligned to the plane of the viewport.
  MBXTextPitchAlignmentViewport = 1,
/// Automatically matches the value of {@link TEXT_ROTATION_ALIGNMENT}.
  MBXTextPitchAlignmentAuto = 2,
};

/// In combination with <code>symbol-placement</code>, determines the rotation behavior of the individual glyphs forming the text.
typedef SWIFT_ENUM(NSInteger, MBXTextRotationAlignment, open) {
/// When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_POINT}, aligns text east-west. When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_LINE} or {@link Property#SYMBOL_PLACEMENT_LINE_CENTER}, aligns text x-axes with the line.
  MBXTextRotationAlignmentMap = 0,
/// Produces glyphs whose x-axes are aligned with the x-axis of the viewport, regardless of the value of {@link SYMBOL_PLACEMENT}.
  MBXTextRotationAlignmentViewport = 1,
/// When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_POINT}, this is equivalent to {@link Property#TEXT_ROTATION_ALIGNMENT_VIEWPORT}. When {@link SYMBOL_PLACEMENT} is set to {@link Property#SYMBOL_PLACEMENT_LINE} or {@link Property#SYMBOL_PLACEMENT_LINE_CENTER}, this is equivalent to {@link Property#TEXT_ROTATION_ALIGNMENT_MAP}.
  MBXTextRotationAlignmentAuto = 2,
};

/// Specifies how to capitalize text, similar to the CSS <code>text-transform</code> property.
typedef SWIFT_ENUM(NSInteger, MBXTextTransform, open) {
/// The text is not altered.
  MBXTextTransformNone = 0,
/// Forces all letters to be displayed in uppercase.
  MBXTextTransformUppercase = 1,
/// Forces all letters to be displayed in lowercase.
  MBXTextTransformLowercase = 2,
};

/// Controls the frame of reference for <code>text-translate</code>.
typedef SWIFT_ENUM(NSInteger, MBXTextTranslateAnchor, open) {
/// The text is translated relative to the map.
  MBXTextTranslateAnchorMap = 0,
/// The text is translated relative to the viewport.
  MBXTextTranslateAnchorViewport = 1,
};

/// The property allows control over a symbol’s orientation. Note that the property values act as a hint, so that a symbol whose language doesn’t support the provided orientation will be laid out in its natural orientation. Example: English point symbol will be rendered horizontally even if array value contains single ‘vertical’ enum value. For symbol with point placement, the order of elements in an array define priority order for the placement of an orientation variant. For symbol with line placement, the default text writing mode is either [‘horizontal’, ‘vertical’] or [‘vertical’, ‘horizontal’], the order doesn’t affect the placement.
typedef SWIFT_ENUM(NSInteger, MBXTextWritingMode, open) {
/// If a text’s language supports horizontal writing mode, symbols would be laid out horizontally.
  MBXTextWritingModeHorizontal = 0,
/// If a text’s language supports vertical writing mode, symbols would be laid out vertically.
  MBXTextWritingModeVertical = 1,
};


SWIFT_CLASS("_TtC13MapboxMapObjC8MBXValue")
@interface MBXValue : NSObject
- (nonnull instancetype)initWithConstant:(NSObject * _Nonnull)constant OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithExpression:(MBXExpression * _Nonnull)expression OBJC_DESIGNATED_INITIALIZER;
+ (MBXValue * _Nonnull)constant:(NSObject * _Nonnull)constant SWIFT_WARN_UNUSED_RESULT;
+ (MBXValue * _Nonnull)expression:(MBXExpression * _Nonnull)expression SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



typedef SWIFT_ENUM(NSInteger, MBXVisibility, open) {
/// The layer is shown.
  MBXVisibilityVisible = 0,
/// The layer is not shown.
  MBXVisibilityNone = 1,
};

@class MBMResourceOptions;
@class MapInitOptions;
@class MBMMapOptions;
@class MBMCameraOptions;
@class NSURL;

SWIFT_CLASS("_TtC13MapboxMapObjC21MapInitOptionsBuilder")
@interface MapInitOptionsBuilder : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MBMResourceOptions * _Nonnull defaultResourceOptions;)
+ (MBMResourceOptions * _Nonnull)defaultResourceOptions SWIFT_WARN_UNUSED_RESULT;
+ (MapInitOptionsBuilder * _Nonnull)create SWIFT_WARN_UNUSED_RESULT;
- (MapInitOptions * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (MapInitOptionsBuilder * _Nonnull)resourceOptions:(MBMResourceOptions * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (MapInitOptionsBuilder * _Nonnull)accessToken:(NSString * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (MapInitOptionsBuilder * _Nonnull)mapOptions:(MBMMapOptions * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (MapInitOptionsBuilder * _Nonnull)cameraOptions:(MBMCameraOptions * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (MapInitOptionsBuilder * _Nonnull)styleUriString:(NSString * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (MapInitOptionsBuilder * _Nonnull)styleUri:(NSURL * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
/// Mapbox Streets is a general-purpose style with detailed road and transit networks.
- (MapInitOptionsBuilder * _Nonnull)styleStreets SWIFT_WARN_UNUSED_RESULT;
/// Mapbox Outdoors is a general-purpose style tailored to outdoor activities.
- (MapInitOptionsBuilder * _Nonnull)styleOutdoors SWIFT_WARN_UNUSED_RESULT;
/// Mapbox Light is a subtle, light-colored backdrop for data visualizations.
- (MapInitOptionsBuilder * _Nonnull)styleLight SWIFT_WARN_UNUSED_RESULT;
/// Mapbox Dark is a subtle, dark-colored backdrop for data visualizations.
- (MapInitOptionsBuilder * _Nonnull)styleDark SWIFT_WARN_UNUSED_RESULT;
/// The Mapbox Satellite style is a base-map of high-resolution satellite and aerial imagery.
- (MapInitOptionsBuilder * _Nonnull)styleSatellite SWIFT_WARN_UNUSED_RESULT;
/// The Mapbox Satellite Streets style combines the high-resolution satellite and aerial imagery
/// of Mapbox Satellite with unobtrusive labels and translucent roads from Mapbox Streets.
- (MapInitOptionsBuilder * _Nonnull)styleSatelliteStreets SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
- (void)setTerrain:(MBXTerrain * _Nonnull)value onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
@end


@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
- (void)addFillExtrusionLayer:(NSString * _Nonnull)id configure:(SWIFT_NOESCAPE void (^ _Nonnull)(FillExtrusionLayerBuilder * _Nonnull))configure onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
@end


@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
- (void)setCameraTo:(MBMCameraOptions * _Nonnull)cameraOptions;
@end

@class RasterDemSourceBuilder;

@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
- (void)addRasterDemSource:(NSString * _Nonnull)id configure:(SWIFT_NOESCAPE void (^ _Nonnull)(RasterDemSourceBuilder * _Nonnull))configure onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
@end


@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
- (void)ornamentsOptionsScaleBarVisibility:(enum MBXOrnamentVisibility)value;
@end

@class SkyLayerBuilder;

@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
- (void)addSkyLayer:(NSString * _Nonnull)id configure:(SWIFT_NOESCAPE void (^ _Nonnull)(SkyLayerBuilder * _Nonnull))configure onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
@end


@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
- (void)preferredFrameRateRange:(CAFrameRateRange)value;
- (NSArray<NSNumber *> * _Nonnull)mapboxMapDebugOptions SWIFT_WARN_UNUSED_RESULT;
- (void)mapboxMapDebugOptions:(NSArray<NSNumber *> * _Nonnull)value;
@end

@protocol LocationPermissionsDelegate;
@class Puck2DConfigurationBuilder;

@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
- (void)locationDelegate:(id <LocationPermissionsDelegate> _Nonnull)delegate;
- (void)locationRequestTemporaryFullAccuracyPermissions:(NSString * _Nonnull)customKey;
- (void)puck2D:(void (^ _Nullable)(Puck2DConfigurationBuilder * _Nonnull))build;
- (void)puckBearingSource:(enum MBXPuckBearingSource)source;
@end

@protocol MBMCustomLayerHost;
@class NSDictionary;

@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
- (void)addCustomLayer:(NSString * _Nonnull)id layerHost:(id <MBMCustomLayerHost> _Nonnull)layerHost below:(NSString * _Nonnull)belowLayerId onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
- (void)addCustomLayer:(NSString * _Nonnull)id layerHost:(id <MBMCustomLayerHost> _Nonnull)layerHost above:(NSString * _Nonnull)aboveLayerId onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
- (void)addCustomLayer:(NSString * _Nonnull)id layerHost:(id <MBMCustomLayerHost> _Nonnull)layerHost at:(NSInteger)index onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
- (void)addLayerBelowWithProperties:(NSDictionary * _Nonnull)properties layerId:(NSString * _Nonnull)layerId onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
- (void)addLayerAboveWithProperties:(NSDictionary * _Nonnull)properties layerId:(NSString * _Nonnull)layerId onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
- (void)addLayerAtWithProperties:(NSDictionary * _Nonnull)properties index:(NSInteger)index onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
@end

@class UIColor;

@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
/// Whether extruded geometries are lit relative to the map or viewport.
- (void)lightAnchor:(enum MBXAnchor)value onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
/// Color tint for lighting extruded geometries.
- (void)lightColor:(UIColor * _Nonnull)value onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
/// Transition property for <code>color</code>
- (void)lightColorTransition:(MBXStyleTransition * _Nonnull)value onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
/// Intensity of lighting (on a scale from 0 to 1). Higher numbers will present as more extreme contrast.
- (void)lightIntensity:(double)value onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
/// Transition property for <code>intensity</code>
- (void)lightIntensityTransition:(MBXStyleTransition * _Nonnull)value onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
/// Position of the light source relative to lit (extruded) geometries, in [r radial coordinate, a azimuthal angle, p polar angle] where r indicates the distance from the center of the base of an object to its light, a indicates the position of the light relative to 0 degree (0 degree when <code>light.anchor</code> is set to <code>viewport</code> corresponds to the top of the viewport, or 0 degree when <code>light.anchor</code> is set to <code>map</code> corresponds to due north, and degrees proceed clockwise), and p indicates the height of the light (from 0 degree, directly above, to 180 degree, directly below).
- (void)lightPosition:(NSArray<NSNumber *> * _Nonnull)value onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
/// Transition property for <code>position</code>
- (void)lightPositionTransition:(MBXStyleTransition * _Nonnull)value onError:(void (^ _Nullable)(NSError * _Nonnull))onError;
@end


@interface MapView (SWIFT_EXTENSION(MapboxMapObjC))
/// The style has been fully loaded, and the map has rendered all visible tiles.
- (MBXCancelable * _Nonnull)onMapLoaded:(void (^ _Nonnull)(id _Nonnull))handler;
/// Describes an error that has occurred while loading the Map. The <code>type</code> property defines what resource could
/// not be loaded and the <code>message</code> property will contain a descriptive error message.
/// In case of <code>source</code> or <code>tile</code> loading errors, <code>source-id</code> will contain the id of the source failing.
/// In case of <code>tile</code> loading errors, <code>tile-id</code> will contain the id of the tile.
- (MBXCancelable * _Nonnull)onMapLoadingError:(void (^ _Nonnull)(id _Nonnull))handler;
/// The map has entered the idle state. The map is in the idle state when there are no ongoing transitions
/// and the map has rendered all requested non-volatile tiles. The event will not be emitted if <code>setUserAnimationInProgress</code>
/// and / or <code>setGestureInProgress</code> is set to <code>true</code>.
- (MBXCancelable * _Nonnull)onMapIdle:(void (^ _Nonnull)(id _Nonnull))handler;
/// The requested style data has been loaded. The <code>type</code> property defines what kind of style data has been loaded.
/// Event may be emitted synchronously, for example, when <code>setStyleJSON</code> is used to load style.
/// Based on an event data <code>type</code> property value, following use-cases may be implemented:
/// <ul>
///   <li>
///     <code>style</code>: Style is parsed, style layer properties could be read and modified, style layers and sources could be
///     added or removed before rendering is started.
///   </li>
///   <li>
///     <code>sprite</code>: Style’s sprite sheet is parsed and it is possible to add or update images.
///   </li>
///   <li>
///     <code>sources</code>: All sources defined by the style are loaded and their properties could be read and updated if needed.
///   </li>
/// </ul>
- (MBXCancelable * _Nonnull)onStyleDataLoaded:(void (^ _Nonnull)(id _Nonnull))handler;
/// The requested style has been fully loaded, including the style, specified sprite and sources’ metadata.
/// Note: The style specified sprite would be marked as loaded even with sprite loading error (An error will be emitted via <code>.mapLoadingError</code>).
/// Sprite loading error is not fatal and we don’t want it to block the map rendering, thus this event will still be emitted if style and sources are fully loaded.
- (MBXCancelable * _Nonnull)onStyleLoaded:(void (^ _Nonnull)(id _Nonnull))handler;
/// A style has a missing image. This event is emitted when the map renders visible tiles and
/// one of the required images is missing in the sprite sheet. Subscriber has to provide the missing image
/// by calling <code>Style/addImage(_:id:sdf:contentInsets:)</code>.
- (MBXCancelable * _Nonnull)onStyleImageMissing:(void (^ _Nonnull)(id _Nonnull))handler;
/// An image added to the style is no longer needed and can be removed using <code>Style/removeImage(withId:)</code>.
- (MBXCancelable * _Nonnull)onStyleImageRemoveUnused:(void (^ _Nonnull)(id _Nonnull))handler;
/// A source data has been loaded.
/// Event may be emitted synchronously in cases when source’s metadata is available when source is added to the style.
/// The <code>id</code> property defines the source id.
/// The <code>type</code> property defines if source’s metadata (e.g., TileJSON) or tile has been loaded. The property of <code>metadata</code>
/// value might be useful to identify when particular source’s metadata is loaded, thus all source’s properties are
/// readable and can be updated before map will start requesting data to be rendered.
/// The <code>loaded</code> property will be set to <code>true</code> if all source’s data required for visible viewport of the map, are loaded.
/// The <code>tile-id</code> property defines the tile id if the <code>type</code> field equals <code>tile</code>.
- (MBXCancelable * _Nonnull)onSourceDataLoaded:(void (^ _Nonnull)(id _Nonnull))handler;
/// The source has been added with <code>Style/addSource(_:id:)</code> or <code>Style/addSource(withId:properties:)</code>.
/// The event is emitted synchronously, therefore, it is possible to immediately
/// read added source’s properties.
- (MBXCancelable * _Nonnull)onSourceAdded:(void (^ _Nonnull)(id _Nonnull))handler;
/// The source has been removed with <code>Style/removeSource(withId:)</code>.
/// The event is emitted synchronously, thus, <code>Style/allSourceIdentifiers</code> will be
/// in sync when the observer receives the notification.
- (MBXCancelable * _Nonnull)onSourceRemoved:(void (^ _Nonnull)(id _Nonnull))handler;
/// The map finished rendering a frame.
/// The <code>render-mode</code> property tells whether the map has all data (<code>full</code>) required to render the visible viewport.
/// The <code>needs-repaint</code> property provides information about ongoing transitions that trigger map repaint.
/// The <code>placement-changed</code> property tells if the symbol placement has been changed in the visible viewport.
- (MBXCancelable * _Nonnull)onRenderFrameStarted:(void (^ _Nonnull)(id _Nonnull))handler;
/// The camera has changed. This event is emitted whenever the visible viewport
/// changes due to the MapView’s size changing or when the camera
/// is modified by calling camera methods. The event is emitted synchronously,
/// so that an updated camera state can be fetched immediately.
- (MBXCancelable * _Nonnull)onRenderFrameFinished:(void (^ _Nonnull)(id _Nonnull))handler;
/// The camera has changed. This event is emitted whenever the visible viewport
/// changes due to the MapView’s size changing or when the camera
/// is modified by calling camera methods. The event is emitted synchronously,
/// so that an updated camera state can be fetched immediately.
- (MBXCancelable * _Nonnull)onEvenCameraChanged:(void (^ _Nonnull)(id _Nonnull))handler;
/// The <code>ResourceRequest</code> event allows client to observe resource requests made by a
/// map or snapshotter.
- (MBXCancelable * _Nonnull)onResourceRequest:(void (^ _Nonnull)(id _Nonnull))handler;
@end


SWIFT_CLASS("_TtC13MapboxMapObjC14MapViewFactory")
@interface MapViewFactory : NSObject
/// :nodoc:
/// See https://developer.apple.com/forums/thread/650054 for context
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (MapView * _Nonnull)createWithFrame:(CGRect)frame options:(MapInitOptions * _Nullable)options SWIFT_WARN_UNUSED_RESULT;
@end


@class Puck2DConfigurationPulsingBuilder;
@class UIImage;

SWIFT_CLASS("_TtC13MapboxMapObjC26Puck2DConfigurationBuilder")
@interface Puck2DConfigurationBuilder : NSObject
- (Puck2DConfigurationBuilder * _Nonnull)setPulsingBuilder:(Puck2DConfigurationPulsingBuilder * _Nullable)builder SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationBuilder * _Nonnull)setPulsing:(SWIFT_NOESCAPE void (^ _Nonnull)(Puck2DConfigurationPulsingBuilder * _Nonnull))build SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationBuilder * _Nonnull)setOpacity:(NSNumber * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationBuilder * _Nonnull)setTopImage:(UIImage * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationBuilder * _Nonnull)setBearingImage:(UIImage * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationBuilder * _Nonnull)setShadowImage:(UIImage * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationBuilder * _Nonnull)setScale:(NSNumber * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationBuilder * _Nonnull)setShowsAccuracyRing:(BOOL)value SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationBuilder * _Nonnull)setAccuracyRingColor:(UIColor * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationBuilder * _Nonnull)setAccuracyRingBorderColor:(UIColor * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13MapboxMapObjC33Puck2DConfigurationPulsingBuilder")
@interface Puck2DConfigurationPulsingBuilder : NSObject
- (Puck2DConfigurationPulsingBuilder * _Nonnull)setColor:(UIColor * _Nullable)color SWIFT_WARN_UNUSED_RESULT;
- (Puck2DConfigurationPulsingBuilder * _Nonnull)setRadiusWithValue:(NSNumber * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13MapboxMapObjC22RasterDemSourceBuilder")
@interface RasterDemSourceBuilder : NSObject
- (RasterDemSourceBuilder * _Nonnull)url:(NSString * _Nullable)value;
- (RasterDemSourceBuilder * _Nonnull)tiles:(NSArray<NSString *> * _Nullable)value;
- (RasterDemSourceBuilder * _Nonnull)bounds:(NSArray<NSNumber *> * _Nullable)value;
- (RasterDemSourceBuilder * _Nonnull)minzoom:(double)value;
- (RasterDemSourceBuilder * _Nonnull)maxzoom:(double)value;
- (RasterDemSourceBuilder * _Nonnull)tileSize:(double)value;
- (RasterDemSourceBuilder * _Nonnull)attribution:(NSString * _Nullable)value;
- (RasterDemSourceBuilder * _Nonnull)encoding:(enum MBXEncoding)value;
- (RasterDemSourceBuilder * _Nonnull)volatile:(BOOL)value;
- (RasterDemSourceBuilder * _Nonnull)prefetchZoomDelta:(double)value;
- (RasterDemSourceBuilder * _Nonnull)minimumTileUpdateInterval:(double)value;
- (RasterDemSourceBuilder * _Nonnull)maxOverscaleFactorForParentTiles:(double)value;
- (RasterDemSourceBuilder * _Nonnull)tileRequestsDelay:(double)value;
- (RasterDemSourceBuilder * _Nonnull)tileNetworkRequestsDelay:(double)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC13MapboxMapObjC15SkyLayerBuilder")
@interface SkyLayerBuilder : NSObject
- (void)filter:(MBXExpression * _Nullable)value;
- (void)source:(NSString * _Nullable)value;
- (void)sourceLayer:(NSString * _Nullable)value;
- (void)minZoom:(NSNumber * _Nullable)value;
- (void)maxZoom:(NSNumber * _Nullable)value;
- (void)visibility:(MBXValue * _Nullable)value;
- (void)skyAtmosphereColor:(MBXValue * _Nullable)value;
- (void)skyAtmosphereHaloColor:(MBXValue * _Nullable)value;
- (void)skyAtmosphereSun:(MBXValue * _Nullable)value;
- (void)skyAtmosphereSunIntensity:(MBXValue * _Nullable)value;
- (void)skyGradient:(MBXValue * _Nullable)value;
- (void)skyGradientCenter:(MBXValue * _Nullable)value;
- (void)skyGradientRadius:(MBXValue * _Nullable)value;
- (void)skyOpacity:(MBXValue * _Nullable)value;
- (void)skyOpacityTransition:(MBXStyleTransition * _Nullable)value;
- (void)skyType:(MBXValue * _Nullable)value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
